add brandfarm.com.ng
mitchellkrogza/phishing pull request #116
Opened 2022-01-24 21:50 UTC by Zachinquarantine

## Domain/URL/IP(s) where you have found the Phishing:
URL: hxxps://www.brandfarm.com.ng/wfargo/wfargo/wellsrgo/wiret.html?check=yes&denation=nba/accountopening/ApplicatStartup/Applinow5inpage&update=&cookiecheck=

## Related external source
https://scammer.info/t/wells-fargo-phishing/88823

## Describe the issue
Wells Fargo bank phishing page.

### Screenshot
![slika](https://user-images.githubusercontent.com/69423184/150870786-9ddfc745-f2b7-4bb6-8475-dabc51cd7d26.png)

2022-01-26 15:18 UTC, spirillen requested changes
Hey friend, nice to se you back active :wave: 

After visiting this domain and done a little curl / whois digging I wouldn't mind blacklisting this domain entirely in the `add-wildcard-domain`

Not at least because of the complete timeout andHTTP code 403 on main domain

```
curl -I http(s)?://brandfarm.com.ng
HTTP/2 403 
content-type: text/html; charset=iso-8859-1
date: Wed, 26 Jan 2022 15:14:37 GMT
server: Apache
```

2022-01-27 01:53 UTC, Zachinquarantine commented
> I wouldn't mind blacklisting this domain entirely in the `add-wildcard-domain`

Done!

2022-01-27 01:54 UTC, spirillen approved these changes

2022-01-27 01:54 UTC, merged

2022-01-27 01:54 UTC, spirillen commented
Super, thanks