add possible linkedin phishing site
mitchellkrogza/phishing pull request #117
Opened 2022-01-26 06:59 UTC by allaway

Stumbled upon this by accident. Redirects to an unknown, possibly malicious site (http://www6.linkedinin.com).

## Domain/URL/IP(s) where you have found the Phishing:
linkedinin.com
www6.linkedinin.com

## Related external source
n/a, discovered myself by accident...

## Describe the issue
This typo is a valid domain that redirects to a blank website that does not appear to be affiliated w/linkedin. 

### Screenshot
<--! If you feel a screenshot can say more than 1000 hard drives, do please feel free to add it here :smiley:

**TIP**: Place your mouse on the line just above the `</details>` 
and paste your screenshot and make sure that there is at least one
line spacing before and after the image code line. The tip will add"
one line after the paste :wink: -->

<details><summary>Click to expand</summary>

</details>

2022-01-26 15:13 UTC, spirillen requested changes
Please add this one to the https://github.com/mitchellkrogza/phishing/blob/main/add-wildcard-domain as `linkedinin.com` that will protect against any  subdomain renaming

2022-01-27 06:06 UTC, allaway commented on add-domain
> +linkedinin.com
```suggestion
```

2022-01-27 06:06 UTC, allaway commented on add-domain
> +www6.linkedinin.com
```suggestion
```

2022-01-27 06:08 UTC, allaway commented
@mitchellkrogza , thanks for the quick review! Hopefully I followed your request correctly.

2022-01-27 06:18 UTC, allaway commented
@spirillen thanks for the quick review! Hopefully I followed your request correctly.

2022-01-30 05:26 UTC, spirillen approved these changes

2022-01-30 05:26 UTC, merged

2022-01-30 05:27 UTC, spirillen commented
> @spirillen thanks for the quick review! Hopefully I followed your request correctly.

Seems good, just had a few days off :+1: