Update add-domain
mitchellkrogza/phishing pull request #183
Opened 2022-12-04 21:02 UTC by gafty

## Domain/URL/IP(s) where you have found the Phishing:

bitelon.net

## Impersonated domain

## Related external source

## Describe the issue

### Screenshot

<details><summary>Click to expand</summary>

</details>

2022-12-06 16:27 UTC, spirillen commented
You need to fill out the form

2023-01-04 16:11 UTC, FMS2309 commented
Which form address please

2023-01-04 16:19 UTC, FMS2309 commented
My website is a false positive, I need it to be unblocked from the phishing database. What do I need to do? which form to fill?

2023-01-04 16:28 UTC, FMS2309 requested changes
My site has no virus is a false positive. By please remover the lock
www.wcei.com.br

2023-01-04 18:30 UTC, FMS2309 commented on add-domain
> +bitelon.net
www.wcei.com.br

2023-01-05 12:40 UTC, FMS2309 commented
Domain/URL/IP(s) where you have found the Phishing:
www.wcei.com.br   (vírus total)

Impersonated domain:  www.wcei.com.br
Related external source: virus total
Describe the issue:   false positive
[https://www.virustotal.com/gui/url/cf8faa590e8b45d45338f241bc94886c31e899854770925812ce1f384e4923a2?nocache=1](url)

2023-01-30 16:16 UTC, spirillen commented
![image](https://user-images.githubusercontent.com/44526987/215532147-1ec634a3-6978-4978-bf85-7503db10d4d0.png)

2023-03-08 19:02 UTC, closed without merging