Fake Webmail
mitchellkrogza/phishing pull request #30
Opened 2021-07-07 14:40 UTC by wagonza

2021-07-07 17:00 UTC, spirillen requested changes
I do not as such have anything against you submit both url and domain, I'll guess one of them should be sufficient.

@mitchellkrogza it yours to decide if both are useful.

Note: To see the Phishing site in question, use this url: `https://alignmentlidjsonpanz.web.app/login.html`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/124801340-04c37800-df57-11eb-8478-ebebeac95468.png)

</details>

2021-07-08 09:32 UTC, wagonza commented
> I do not as such have anything against you submit both url and domain, I'll guess one of them should be sufficient.
> 
> @mitchellkrogza it yours to decide if both are useful.
> 
> Note: To see the Phishing site in question, use this url: `https://alignmentlidjsonpanz.web.app/login.html`

Removed the link and will submit one in future.

2021-07-10 20:48 UTC, spirillen requested changes

2021-07-10 20:48 UTC, spirillen commented on add-link
> +https://carlicence.co.za/wp-admin/shiplabel/
Seems fixed to me

![image](https://user-images.githubusercontent.com/44526987/125175784-b0c2c880-e1ce-11eb-867b-82ae2a78a43b.png)

2021-07-10 20:48 UTC, spirillen commented on add-domain
> +data-base.cf
I can neither confirm or not. the `https://whois.freenom.com/en/whois.html` seems currently down 

drill data-base.cf @9.9.9.9
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 43037
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; data-base.cf.        IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
cf.     5       IN      SOA     a.ns.cf. kohilaire.socatel.cf. 1625949359 10800 3600 604800 5

2021-09-18 18:30 UTC, spirillen commented
Can't find any active urls domains

2021-09-18 18:30 UTC, closed without merging