mondialerelayformulaire.com
mitchellkrogza/phishing pull request #35
Opened 2021-07-20 13:24 UTC by Totorh

Phishing site for debit cards in Belgium, copying mondialrelay.be

2021-07-20 15:09 UTC, spirillen requested changes
Not for change, but need more info for confirmation

2021-07-20 15:09 UTC, spirillen commented on add-domain
>  totaltrkonups2298.fitritomoastramencostea.com
Can only see a default Apache Centos page. Do you have any other information for confirmation?

2021-11-28 14:17 UTC, iam-py-test commented
@Totorh any update?

2021-12-03 01:47 UTC, spirillen commented
Closed as unresponsive

2021-12-03 01:47 UTC, closed without merging